
name: avymart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  uuid: ^4.5.1
  firebase_storage: ^13.0.3
  firebase_app_check: ^0.4.1+1
  pinput: ^5.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
